name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  gh_tagged_release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Build"
        run: |
          npm install
          npm run build-single-file
          mv dist/index.html collisions.html

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            collisions.html