name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  gh_tagged_release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: "Build"
        run: |
          npm install
          npm run build-single-file
          mv dist/index.html collisions.html

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            collisions.html